ALTER TABLE "Offer" ADD COLUMN "estimatedPoints" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Offer" ADD COLUMN "scoreBreakdown" TEXT NOT NULL DEFAULT '[]';

ALTER TABLE "Assignment" ADD COLUMN "estimatedPoints" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Assignment" ADD COLUMN "scoreBreakdown" TEXT NOT NULL DEFAULT '[]';

ALTER TABLE "ScoreEvent" ADD COLUMN "breakdown" TEXT NOT NULL DEFAULT '[]';
