ALTER TABLE "Driver" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Driver" ADD COLUMN "longitude" DOUBLE PRECISION;
ALTER TABLE "Driver" ADD COLUMN "locationAccuracyMeters" DOUBLE PRECISION;
ALTER TABLE "Driver" ADD COLUMN "locationUpdatedAt" TIMESTAMP(3);

ALTER TABLE "Store" ADD COLUMN "latitude" DOUBLE PRECISION NOT NULL DEFAULT 34.981;
ALTER TABLE "Store" ADD COLUMN "longitude" DOUBLE PRECISION NOT NULL DEFAULT 135.962;

ALTER TABLE "Order" ADD COLUMN "dropoffLatitude" DOUBLE PRECISION NOT NULL DEFAULT 34.978;
ALTER TABLE "Order" ADD COLUMN "dropoffLongitude" DOUBLE PRECISION NOT NULL DEFAULT 135.968;
