ALTER TABLE "Driver" ADD COLUMN "latitude" REAL;
ALTER TABLE "Driver" ADD COLUMN "longitude" REAL;
ALTER TABLE "Driver" ADD COLUMN "locationAccuracyMeters" REAL;
ALTER TABLE "Driver" ADD COLUMN "locationUpdatedAt" DATETIME;

ALTER TABLE "Store" ADD COLUMN "latitude" REAL NOT NULL DEFAULT 34.981;
ALTER TABLE "Store" ADD COLUMN "longitude" REAL NOT NULL DEFAULT 135.962;

ALTER TABLE "Order" ADD COLUMN "dropoffLatitude" REAL NOT NULL DEFAULT 34.978;
ALTER TABLE "Order" ADD COLUMN "dropoffLongitude" REAL NOT NULL DEFAULT 135.968;
